.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SPLIT 1 "september 18, 2010" "MAME 0139"

.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)

.SH "NAME"
split \- File splitter/joiner with hashes.

.SH "SYNOPSIS"
.TP
Split file into parts:
.br
.B split
.B -split
.I big_file
.I base_name
.B size
.TP
Join file parts into original file:
.br
.B split
.B -join
.I split_file
.I [output_file]
.TP
Verify a split file:
.br
.B split
.B -verify
.I splitfile

.SH "DESCRIPTION"
.TP
Simple utility to split files and verify/join splitted parts.
.br
.B big_file
is the large file you wish to split.
.br
.B base_name
is the base path and name to assign to the split files.
.br
.B size
is the optional split size, in MB (100MB is the default).
.br
.B split_file
is the name of the
.B base_name
.split generated with
.B -split
.
.br
.B output_file
is the name of the file to output (defaults to original name).


.SH "COPYRIGHT"
Copyright \(co 2008 Aaron Giles. BSD License.

.SH "AUTHOR"
Written by Aaron Giles.

.sp 3
This manual page was written by Ludovic Lechapt <ludomatic@gmail.com>,
for the Debian project but may be used by others.
