.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH UNIDASM 1 "December 20, 2010" "MAME 0140"

.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)

.SH "NAME"
unidasm \- Generic MAME disassembler.

.SH "SYNOPSIS"
.B unidasm
.I filename
.B -arch <architecture>
.B [-basepc <pc>]
.B [-mode <n>]
.B [-norawbytes]
.B [-flipped]
.B [-upper]
.B [-lower]

.SH "DESCRIPTION"
Disassembler for various architectures used in MAME.
.sp 2

Supported architectures are adsp21xx, alpha8201, arm, arm7arm, arm7thumb, asap, avr8, ccpu, cdp1802, cop410, cop420, cop444, cp1610, cquestsnd, cquestrot, cquestlin, dsp32c, dsp56k, hyperstone_generic, esrip, f8, g65816_generic, h6280, h8, hd6309, i4004, i8008, i8085, x86_16, x86_32, x86_64, i960, jaguargpu, jaguardsp, konami, lh5801, lr35902, m37710_generic, m6502, m65sc02, m65c02, m65ce02, m6510, deco16, m4510, m6800, m6801, m6802, m6803, hd63701, nsc8105, m68000, m68008, m68010, m68020, m68030, m68040, m6805, m6809, mb86233, mb88, mcs48, upi41, i8051, i8052, i80c51, i80c52, ds5002fp, minx, mips3be, mips3le, psxcpu_generic, r3000be, r3000le, nec_generic, pdp1, tx0_64kw, tx0_8kw, pic16c5x, pic16c62x, powerpc, rsp, s2650, saturn, sc61860, scmp, se3208, sh2, sh4, sharc, sm8500, spc700, ssem, ssp1601, t11, t90, tlcs900, tms0980, tms1000, tms1100, 32010, tms32025, tms32031, 32051, 34010, 34020, 57002, 7000, upd7810, upd7807, upd7801, upd78c05, v60, v70, v810, z180, z8000, z80 and z8.

.SH "SEE ALSO"
\fBmame\fR(1) 

.SH "COPYRIGHT"
Copyright \(co 2008 Aaron Giles. BSD License.

.SH "AUTHOR"
Written by Aaron Giles.

.sp 3
This manual page was written by Ludovic Lechapt <ludomatic@gmail.com>,
for the Debian project but may be used by others.
