mame usr/games
debian/install/mame.xpm usr/share/pixmaps
debian/install/mame.desktop usr/share/applications
debian/mame.ini etc/mame
hash.mame/* usr/share/games/mame/hash
src/osd/sdl/keymaps/*.txt usr/share/games/mame/keymaps

./debian/install/hicolor/16x16/apps/mame.png usr/share/icons/hicolor/16x16/apps
./debian/install/hicolor/22x22/apps/mame.png usr/share/icons/hicolor/22x22/apps
./debian/install/hicolor/24x24/apps/mame.png usr/share/icons/hicolor/24x24/apps
./debian/install/hicolor/32x32/apps/mame.png usr/share/icons/hicolor/32x32/apps
./debian/install/hicolor/48x48/apps/mame.png usr/share/icons/hicolor/48x48/apps
./debian/install/hicolor/72x72/apps/mame.png usr/share/icons/hicolor/72x72/apps
./debian/install/hicolor/128x128/apps/mame.png usr/share/icons/hicolor/128x128/apps

